### PR TITLE
MNT Use GitHub Actions CI

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/gha-ci/issues/11<br /><br />Workflow run https://github.com/creative-commoners/doorman/actions?query=branch%3Apulls%2F3.1%2Fmodule-standards

### CODE REVIEW

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
Need to add a phpcs file for linting

**Comment by emteknetnz** [comment]
Updated

**Comment by GuySartorelli** [comment]
I'm confused... you've renamed the phpunit file (which I don't think was necessary) but didn't add a phpcs file?

**Comment by emteknetnz** [comment]
Have added the phpcs config file

**Review by GuySartorelli — APPROVED** [review]
Looks like codesniffer needs to be added too, but that can be handled separately since we're treating failures separately from adding ci config.

**Pull request merged**
