### PR TITLE
Added GroupProcessManager

### PR DESCRIPTION
**Pull request by assertchris**
@tractorcow would you mind giving this a bit of peer review?

### CODE REVIEW

**Comment by tractorcow** [comment]
The code looks fine, but some additional docs would help with review. Could you at least add classdocs to describe the purpose?

**Comment by assertchris** [comment]
Good point - I'll add examples to the md docs.

**Comment by assertchris** [comment]
@tractorcow how about [that](https://github.com/asyncphp/doorman/pull/8/files#diff-d12f29adbdaa47585c841383c44cbc51R1)?

**Comment by tractorcow** [comment]
Sure :dancer:

**Pull request merged**
